apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: '[deployment]-[stage]' # next stage would be '[deployment]-[stage]-[next_stage]'
spec:
  interval: 5m0s
  path: ./_deploy/[deployment]/
  prune: true
  sourceRef:
    kind: GitRepository
    name: momentum